### ISSUE TITLE
The reoptimization period has to be a multiple of the rebalancing period.

### ISSUE THREAD

**Issue by MislavSag** [dppalomar/portfolioBacktest#11]
I would like to backtest simple momentum strategy. I would like to buy 10% osf stocks with highest mmentum (say half year return).

I would like to rebalance every month (buy on the begining of the month).

Here is my try:
```
data("dataset10")
quintile_portfolio_fun <- function(dataset, w_current) {
  X <- diff(log(dataset$adjusted))[-1]  # compute log returns
  N <- ncol(X)
  # design quintile portfolio
  ranking <- sort(colMeans(X), decreasing = TRUE, index.return = TRUE)$ix
  w <- rep(0, N)
  w[ranking[1:round(N/5)]] <- 1/round(N/5)
  return(w)
}
portfolios <- list("Quintile"  = quintile_portfolio_fun)
bt <- portfolioBacktest(portfolios, 
                        my_dataset_list, 
                        benchmark = c("1/N", "index"), 
                        lookback = 252 / 2, 
                        rebalance_every = 22)
```
but I get an error:
```
Backtesting 1 portfolios over 5 datasets (periodicity = daily data)...
Error in (function (portfolio_fun, data, price_name, shortselling, leverage,  : 
  The reoptimization period has to be a multiple of the rebalancing period.
```
I set `rebalance_every = 22` because I wnt monthly rebalancing and I set `ookback = 252 / 2` because I want to look half year momentum. Or should I set half year inside `quintile_portfolio_fun ` function, something like:
```
ranking <- sort(colMeans(tail(X, 22)), decreasing = TRUE, index.return = TRUE)$ix
```

**Comment by dppalomar** [comment]
Rebalancing and reoptimizing are two different things. Reoptimizing is how often the portfolio gets to be recomputed (your portfolio function will be called). But then you could possibly rebalance more frequently than you reoptimize your portfolio (this is because naturally your initial portfolio will change over time as the prices change, so you may want to reset the portfolio to the one you initially designed again).

In your case, you should then set both `reoptimize_every = 22` and `rebalance_every = 22`.
